const URL = 'https://apdjueobqyodbgiwntdo.supabase.co'
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZGp1ZW9icXlvZGJnaXdudGRvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzgwMzc3MywiZXhwIjoyMDg5Mzc5NzczfQ.3ICQWkRJ1ltiLfcEP3SDfYU26wx1A61oIb4oY-GECMM'
const H = { 'apikey': KEY, 'Authorization': `Bearer ${KEY}`, 'Content-Type': 'application/json' }

async function run(label, sql) {
  const r = await fetch(`${URL}/rest/v1/rpc/run_migration`, { method: 'POST', headers: H, body: JSON.stringify({ sql }) })
  const t = await r.text()
  console.log(`[${r.status === 204 ? 'OK' : r.status}] ${label}${r.status !== 204 ? ' ' + t : ''}`)
}

const steps = [
  ['industries', `CREATE TABLE IF NOT EXISTS industries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parent_id UUID REFERENCES industries(id) ON DELETE CASCADE, name VARCHAR(100) NOT NULL, level INTEGER NOT NULL DEFAULT 1 CHECK (level IN (1, 2, 3)), sort_order INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`],
  ['contents_type', `ALTER TABLE contents DROP CONSTRAINT IF EXISTS contents_type_check; ALTER TABLE contents ADD CONSTRAINT contents_type_check CHECK (type IN ('blog', 'threads', 'instagram', 'facebook', 'video_script', 'script'))`],
  ['contents_status', `ALTER TABLE contents DROP CONSTRAINT IF EXISTS contents_status_check; ALTER TABLE contents ADD CONSTRAINT contents_status_check CHECK (status IN ('draft', 'generated', 'confirmed', 'edited', 'scheduled', 'published', 'failed'))`],
  ['contents_cols', `ALTER TABLE contents ADD COLUMN IF NOT EXISTS project_id UUID; ALTER TABLE contents ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ; ALTER TABLE contents ADD COLUMN IF NOT EXISTS revision_note TEXT`],
  ['channels', `ALTER TABLE channels DROP CONSTRAINT IF EXISTS channels_platform_check; ALTER TABLE channels ADD CONSTRAINT channels_platform_check CHECK (platform IN ('instagram', 'threads', 'youtube', 'naver_blog', 'kakao', 'facebook'))`],
  ['usage_logs', `ALTER TABLE usage_logs DROP CONSTRAINT IF EXISTS usage_logs_action_type_check; ALTER TABLE usage_logs ADD CONSTRAINT usage_logs_action_type_check CHECK (action_type IN ('content_create', 'keyword_analyze', 'image_generate', 'publish', 'draft_generate', 'title_generate', 'image_script_generate', 'video_script_generate', 'quality_score', 'content_revise'))`],
  ['projects', `CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, keyword_id UUID REFERENCES keywords(id) ON DELETE SET NULL, keyword_text VARCHAR(200), business_type VARCHAR(10) NOT NULL DEFAULT 'B2C' CHECK (business_type IN ('B2B', 'B2C')), current_step INTEGER DEFAULT 1 CHECK (current_step BETWEEN 1 AND 7), step_status JSONB NOT NULL DEFAULT '{"s1":"pending","s2":"pending","s3":"pending","s4":"pending","s5":"pending","s6":"pending","s7":"pending"}', topic_type VARCHAR(30) CHECK (topic_type IN ('info', 'intro', 'service', 'product')), selected_title VARCHAR(500), title_candidates JSONB, custom_prompt TEXT, prompt_mode VARCHAR(20) DEFAULT 'combine' CHECK (prompt_mode IN ('priority', 'combine', 'reference')), draft_content TEXT, content_ids JSONB DEFAULT '{}', settings_snapshot JSONB, status VARCHAR(20) DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'archived')), confirmed_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`],
  ['image_scripts', `CREATE TABLE IF NOT EXISTS image_scripts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, content_id UUID REFERENCES contents(id) ON DELETE SET NULL, channel VARCHAR(20) NOT NULL, ai_tool VARCHAR(50) NOT NULL DEFAULT 'midjourney', image_size VARCHAR(30) NOT NULL DEFAULT '1080x1080', image_style VARCHAR(20) NOT NULL DEFAULT 'photo' CHECK (image_style IN ('photo', 'illustration')), style_detail VARCHAR(100), prompts JSONB NOT NULL DEFAULT '[]', thumbnail_prompt TEXT, status VARCHAR(20) DEFAULT 'generated' CHECK (status IN ('generating', 'generated', 'edited')), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`],
  ['video_scripts', `CREATE TABLE IF NOT EXISTS video_scripts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, content_id UUID REFERENCES contents(id) ON DELETE SET NULL, format VARCHAR(20) NOT NULL DEFAULT 'short' CHECK (format IN ('short', 'normal')), target_channel VARCHAR(20) NOT NULL DEFAULT 'youtube', scene_count INTEGER NOT NULL DEFAULT 4 CHECK (scene_count BETWEEN 1 AND 5), scene_duration INTEGER NOT NULL DEFAULT 5 CHECK (scene_duration BETWEEN 3 AND 10), total_duration INTEGER, image_style VARCHAR(20) DEFAULT 'photo' CHECK (image_style IN ('photo', 'illustration')), style_detail VARCHAR(100), storyboard JSONB NOT NULL DEFAULT '[]', full_script TEXT, status VARCHAR(20) DEFAULT 'generated' CHECK (status IN ('generating', 'generated', 'edited')), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`],
  ['user_prompts', `CREATE TABLE IF NOT EXISTS user_prompts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, step VARCHAR(30) NOT NULL, prompt_text TEXT NOT NULL, mode VARCHAR(20) DEFAULT 'combine' CHECK (mode IN ('priority', 'combine', 'reference')), is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(user_id, step))`],
  ['indexes', `CREATE INDEX IF NOT EXISTS idx_industries_parent ON industries(parent_id); CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id); CREATE INDEX IF NOT EXISTS idx_projects_user_status ON projects(user_id, status); CREATE INDEX IF NOT EXISTS idx_contents_project ON contents(project_id); CREATE INDEX IF NOT EXISTS idx_image_scripts_project ON image_scripts(project_id); CREATE INDEX IF NOT EXISTS idx_video_scripts_project ON video_scripts(project_id); CREATE INDEX IF NOT EXISTS idx_user_prompts_user ON user_prompts(user_id)`],
  ['rls', `ALTER TABLE industries ENABLE ROW LEVEL SECURITY; ALTER TABLE projects ENABLE ROW LEVEL SECURITY; ALTER TABLE image_scripts ENABLE ROW LEVEL SECURITY; ALTER TABLE video_scripts ENABLE ROW LEVEL SECURITY; ALTER TABLE user_prompts ENABLE ROW LEVEL SECURITY`],
  ['seed', `INSERT INTO industries (parent_id, name, level, sort_order) VALUES (NULL, '음식업', 1, 1), (NULL, '뷰티/헬스', 1, 2), (NULL, '의료', 1, 3), (NULL, '교육', 1, 4), (NULL, '숙박/여행', 1, 5), (NULL, '인테리어/건설', 1, 6), (NULL, '자동차', 1, 7), (NULL, '반려동물', 1, 8), (NULL, '전문직', 1, 9), (NULL, '소매/쇼핑몰', 1, 10), (NULL, '교회/종교', 1, 11), (NULL, '공공/기관', 1, 12), (NULL, 'IT/테크', 1, 13), (NULL, '제조업', 1, 14) ON CONFLICT DO NOTHING`],
  ['plans_starter', `INSERT INTO plans (name, display_name, price_monthly, price_yearly, content_limit, keyword_limit, image_limit, saved_keyword_limit, channel_limit, brand_voice_limit, team_member_limit, history_days, has_api_access, has_priority_support, sort_order) SELECT 'starter', '스타터', 19900, 199000, 50, 100, 30, 100, 3, 3, 0, 90, TRUE, FALSE, 2 WHERE NOT EXISTS (SELECT 1 FROM plans WHERE name = 'starter')`],
  ['plans_premium', `INSERT INTO plans (name, display_name, price_monthly, price_yearly, content_limit, keyword_limit, image_limit, saved_keyword_limit, channel_limit, brand_voice_limit, team_member_limit, history_days, has_api_access, has_priority_support, sort_order) SELECT 'premium', '프리미엄', 0, 0, 9999, 9999, 9999, 9999, 9999, 9999, 10, 9999, TRUE, TRUE, 4 WHERE NOT EXISTS (SELECT 1 FROM plans WHERE name = 'premium')`],
  ['fk_contents', `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_contents_project') THEN ALTER TABLE contents ADD CONSTRAINT fk_contents_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL; END IF; END $$`],
  ['trigger_projects', `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at' AND tgrelid = 'projects'::regclass) THEN CREATE TRIGGER set_updated_at BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION update_updated_at(); END IF; EXCEPTION WHEN undefined_table THEN NULL; END $$`],
  ['trigger_industries', `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at' AND tgrelid = 'industries'::regclass) THEN CREATE TRIGGER set_updated_at BEFORE UPDATE ON industries FOR EACH ROW EXECUTE FUNCTION update_updated_at(); END IF; EXCEPTION WHEN undefined_table THEN NULL; END $$`],
]

for (const [label, sql] of steps) {
  await run(label, sql)
}

// Verify
console.log('\n--- Verify ---')
for (const t of ['industries', 'projects', 'image_scripts', 'video_scripts', 'user_prompts']) {
  const r = await fetch(`${URL}/rest/v1/${t}?select=id&limit=1`, { headers: H })
  console.log(`[${r.status === 200 ? 'OK' : r.status}] ${t}`)
}
console.log('\n=== MIGRATION COMPLETE ===')
